apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "2026.8.3"
    helm:
      releaseName: authentik
      valuesObject:
        authentik:
          existingSecret:
            secretName: authentik-config

        global:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumeMounts:
            - name: authentik-data
              mountPath: /data
          volumes:
            - name: authentik-data
              persistentVolumeClaim:
                claimName: authentik-data

        postgresql:
          enabled: true
          auth:
            enablePostgresUser: false
            username: authentik
            database: authentik
            existingSecret: authentik-config
            secretKeys:
              userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
          primary:
            podSecurityContext:
              enabled: true
              fsGroup: 100
              fsGroupChangePolicy: OnRootMismatch
            containerSecurityContext:
              enabled: true
              runAsUser: 1024
              runAsGroup: 100
              runAsNonRoot: true
              privileged: false
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
            persistence:
              enabled: true
              storageClass: nas-nfs
              accessModes:
                - ReadWriteOnce
              size: 20Gi
            persistentVolumeClaimRetentionPolicy:
              enabled: true
              whenDeleted: Retain
              whenScaled: Retain
          volumePermissions:
            enabled: false

        server:
          replicas: 1
          containerSecurityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

        worker:
          replicas: 1
          containerSecurityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
