apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobtracker-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tyler180/talos-gitops.git
    targetRevision: main
    path: applications/jobtracker-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: jobtracker-demo
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
