apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tyler180/talos-gitops.git
    targetRevision: main
    path: infrastructure/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
