apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:h8gbs34nWb0kiS07OzHS/VKx4RxrweRzPe7kwEr0ifL1mdZ0cfwECHFZtPFufw6NO8+e2PRX3DDS+K8jKnar6w==,iv:I0P6mrYiigga3E5W/TasA7LPDgUm+PfDJKJbQn9kjss=,tag:ZCybTAZ9IXpMyROUYNfU5g==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:TXrCxvKWr864P7F5kv0cL7oIa8E=,iv:9B4bxIY+3hbuHuArSA4eBuhLdl7jGyRMlAZnefrgYic=,tag:kiVcdK7Y+jPdS63JaWlwjw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:QeAiqbaADGiU,iv:0LAc7zP5fkLN6Sjc35zd+TEq0LUBxUBmRN6gNR0tRCc=,tag:x3oPi1Pv7RjsYa4o8LVm5w==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:aghXoKu36Zon,iv:rAgfBTDDNLpZOQYwHD4epOlmyVWp1IHvTc+9EjdLgJQ=,tag:pQTtAZoW4Y603KoUPeb5gQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:bDRanNk4CPW8M9KCrkD03tkslS3dHJcPs+jOrAliFqCTXHuJeWiTw/rZtaqzUlJs,iv:kFMJn++SAIZmIlQfgsme+L+Y4Yni7fVepvLsvcHtk8U=,tag:+jgrwXmYPSisPRakkzpHug==,type:str]
    AUTHENTIK_WEB__BASE_URL: ENC[AES256_GCM,data:l1QoicSlOwcZ+ee9I9YgDFOt31BbdVo7OG8qlRSNwG8=,iv:ZDfjlOfEUiqEyyrmWhYmiGx21LqxZa6SCVK4nc4fPzY=,tag:RGTpYLEZo0XhLYjk4I7GQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGtob05kRHN3R3liV0c4
            T0JBaTAyUnp3RE9UeElwL1ZVQm9VQTVWM2kwCko4ZWY1UHVRemxaYTl6bU1YWEFR
            OVl3c0JYbDF2U2s3MUk2ZHprQ2hXNkkKLS0tIGJYZi9EdHgyak1neFlmZVpDNjQy
            R2R3Q2tUZzBnbzNaR2JRb2h4MmZlR2cK47+CmlSO6XidN7LTuuWfVVTSgSd/oZrK
            U1LUin/F7QFcoJSm91gBnLHASeXqvttSxwEhhAVVAwComJP8smrX5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T05:18:59Z"
    mac: ENC[AES256_GCM,data:rLuXNGgvOScOZ0a0Ow5yJRpls0oaUYg2yhb5wl35Z9zbWoipKMBgli8tdHlxIXYewMobiJ/Y88IQp7ERcocK4G2IXTItAy5xGoB+kjPzl1ZA8zjzoEbhaI0niA4JVPq8rE5BIRk2sfI7B4wVzXR9GCZ/CV4hJ7AS8+zPRAmwc1I=,iv:fam1+Ew4MZDOcH/bCLt78r3dsWucyk8flQlXpFmvHxc=,tag:HZX0RPUq9ZTSNLROY5NBrw==,type:str]
    version: 3.13.3
