apiVersion: v1
data:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:02sGVJvxikoHk77dbTqQytOetqj/8zQOEFGIsw==,iv:AdbxRSUJ+0JWEmwy30zXq5R2JzKClaV6Uq8p3xopVmg=,tag:f/d1EaKNSLMzsiAOixEEBw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:LloWfj1aMYCw0z0t,iv:MPqgyK/qKbA0U3iMr56x8F8oaw5GoYPPsKyAEIOOv3Q=,tag:ITXbZqs56DsZXNd8m14Lng==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:+RIvnkDs/mZKURKh/vNbe2PF92ELLFUk1Oii7MorHrsHAbfei+7oePEL/dNsZ7kuBUS6C18+dpV2/YTA0rNRUQ==,iv:Uq+jNWcocFCHMGzQg5bSez7FiX02JGTH/ig6sN0ycXg=,tag:RXaerVENGu0IA6duXo1W9Q==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:v/NkTe+09mKZDTP4,iv:m9wO9l7gNp+4DI4vbgW+QQQMS4GCR7CXOKpmY5CTkgI=,tag:EJ4uIjDtT6izOLnsqyzLVw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6yfEJOlgZU1EC8JWnxKeDh9ysAuqADGgdQWwS3sjTfm576YUJFk7AqfcVNIvFYZq1fu8UT3CWAwNt/HePeiV8VhxgzEAfCAR3g9dyNZoZlRKNO6BEtL03g==,iv:dijwuKutahXGyJcCWBgeGz+UjXeHxDor0wW7T7dtV50=,tag:788ye0SXz2rN/iRyvWJXWA==,type:str]
    AUTHENTIK_WEB__BASE_URL: ENC[AES256_GCM,data:NIIqGWAhanFsBN6+DfN+sgyYv8yyrYWluIMl4vQH09EMXnxJ,iv:UWX1VHJAJ+eVxP9FLGhh4zPT5Nu32U277hT2y1+H92E=,tag:su3m74uK0b9tTGfRegc1kw==,type:str]
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK0ViclFmM3NBb3VsNERG
            TjBVZG80bkJlMXkvN05IblB0RkFISkpYZ1FrCnNYTmlHTm9nOWx5endBbUZyRHpi
            TkJ4QlFadkNLRE9Kdit2MVFoa013RWMKLS0tIHArZ1RENmRCcEVwdldRMXkrWnZo
            RENnN0RpeFBZMWUwRVZtVjVQU3hHZnMKxuQTWFxULY1K0SmiFQHaquTRK+mwdqdM
            Snxlgqz7Mmf2u+TEjryWpOeHVpHurxSgj/YDur4aZmN7QqCXpkWYVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:38:37Z"
    mac: ENC[AES256_GCM,data:1V5XgIFntdXPllLwHrpmkpOXTmDIpdmT7/6ttmf4p5DmwvFlI7/qHcLhmN5VxaiTZn96eoxJW4E9BlVFkQGfgQvKXBinm8esLq4IDC2h2DLgXCWJwZ7AykJ6+yWG7gnmsioXSU9dlF6UwzLMX6SGHAkSUk4RSgT59angn9pl5+8=,iv:tLVobMfhbFpOzIqaRLDbK/6hPhPR67WduVen/X7xjKM=,tag:vDiiEoHptKOmEsjcnqotYQ==,type:str]
    version: 3.13.3
