apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:dtPqIzQtgma1EUo2JKDZOyULpsh5BQOy0wRwrVhp5a97EbUCl3J1jvxwuesH33TGt4Bi3btaudmAf9fg5yHg6g==,iv:MNzKvcWig7iF5KdwcRyW9PXv5c+trt+QCyghoc7V4Rc=,tag:g1qJJKvP2XPyIVZoS6weFA==,type:str]
    admin-user: ENC[AES256_GCM,data:36EIMUmWosM=,iv:FKzJiaWaATbl4XNgjHD9FxuEGhyxeqxDBzOcWOUTt8s=,tag:bg8dhnOietn/fa+IoDul2A==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bVBWL1h6Z3U2NmhSREpE
            L0E4S2JuTFhIaG1veUdRdHhIRUhmQTUyQlNrCjN3M1d0QkVLMFJKQ1hpN1lIRDV4
            Z0FjaU15US9vRlNDQlBJcXVJbzVuZzQKLS0tIEs2NFJQWWxxY1BxTUg3RGpvaXVx
            Sk9Gc1dBTmNqcTdsSms1TUZRRG41UWMK6v/Y6RQO1TS8SZ/L++rZvt8HaX3/Djnz
            N2tlScquEMKl9j10X4Lbja2fjYSFL+CHeWucSIYvd/rgrKyASIzmIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T15:12:15Z"
    mac: ENC[AES256_GCM,data:GP/TQXPGgUpInF4lOUuAZw/JJpb/3bBJS+lzCceBANsEkvNmpqKWoi5lglx8ebkeAofDscDQaqcKlCfpgREpICDh7ZbgxDOCt+U/IxJxj2BfqxHsAukfiaLgaK5yAXjmAWJ/WPxbynNkAtMzTcL/aOIUhbz/xqdFqTWnMPpXwSQ=,iv:l/8ryl9G6z0776f55gWDlGPZsGCXgQoIjCk2Rx07wAA=,tag:uc78jzt3BtdwP/4XVq4cAQ==,type:str]
    version: 3.13.3
