apiVersion: v1
data:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:f5HMi4TEZRgC6pKKdEA3m+maUizStjFAC8o4nUh9eSjklruxjY0B9puq77ZKETKNVCyuLsM7ZE4=,iv:MdXhg1ddjil4BatHTtOa35yU/bKFTUWGuWv2cgLW7o4=,tag:lAuFHj0rA/RT8MtJhO2XCw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:rqSSaH9TUDae8M04p67FoNqQdaWV5AAWg5Cs2L8yfgfo+E/6r2Ug3g3TeSudcFMOPk+8B6M17APB16JKj3dcGa1i3rXt3kWgz1wtJUXKKEUJx//0zBJB9JpvMMAMScho9PADYQLmmswr8hIRoixAbvxVm0fjuGNNOAhLmKjp2Hgd6NOV5cSpfm1WHyihNATaDXgItlMTyNIFtmeOuGD/pZBanmjZcoWuLmLgDA==,iv:LD8npqBLXrCOtMPmRqxR5sBWu2hLufVD90hth+HoCkw=,tag:0j2Hbyy8q+rbzPX+wyFdxA==,type:str]
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOW00SysweEU1S1hNTW0x
            M2Y4TW1IQXZkbkd3cURobThyWlV2NXN6bFVnCkZMR0dhQ2VHY05tRURxano2WXNx
            VkxVWVFNK1l2UlNiMVRLdHhBMW9nVlEKLS0tIFVHYmhjY3NKRGg5VllhZi9yNEw3
            d29MRitBOUFncmRpMGpXSllNalN2R2cKjJ/oshcBf+AiVXdiDnqKYkyAPDZ5g17Q
            XTh+Ttu/675HUnN8O/c/1tzD4rP+UBr0pIP8IuJDWyob+19W/icPRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:12:37Z"
    mac: ENC[AES256_GCM,data:7kOUroSaA3CukqoteG+nQ0dlS4q9/FOT0IV0Usi7vDcL85+AA2FX9zmUPvzi3p8KHvlF6sG5UNTRj7VNnnBlMsiiTBU573Q3X2KOek6+a+j7Dr83yjxoPoMna4Yo7vKEk8e2Y6aGdUEdqeXaQYYZReVQrjhkxjuJ4PaCPRwKGrA=,iv:dFcdByjDmRa/QOEsgzXFpPJxZxQbcXlRlm8vIo7rHeM=,tag:CWv7ovRUuOs4GGzt4E7jFQ==,type:str]
    version: 3.13.3
