apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: route53-credentials
    namespace: cert-manager
stringData:
    access-key-id: ENC[AES256_GCM,data:LDcvWdJSQoopaGfVUihumDEy/ng=,iv:d1hp5NiEXdRY4qBFdQI/WG+VWdeQvabRjKr0xBXwUsQ=,tag:wOPsSq5aWYjplTrvRX6Ptg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:QCynApxsD3Vv9i/WiXU8PYeD8P9XBpYtQKRAXFcKnglT2dRB9AnYMw==,iv:rflwhFfg/GWZVIB4tsH8trcj4wi1hPhb8QYEnY74z6I=,tag:+7mVcx9UiL25tQ+3NNXw2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMWRQVlgrQlVuSjEyMklp
            WHluSnYyNUdzVTFTOFR3MWhia2lkNjBNcXp3CjF0bXFrYTV4bzhvRFM5ayt2R0lM
            WWJKQlFsUkEzdjFQREIzVVFYVVVTdFUKLS0tIEJzOVpJQXQrM2lXWWo4WURqZVFN
            L21OemFWWnJPZ3EzeDRSQWMwQ3RZdjgKbIXNggH/UDdDmyDg+FCJPoyVjrfQajkA
            jp9ROgp54aphL16hgHoveehlA2cQ6G66R5fB/a6ZFhW7YeZ0ATKHbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:53:55Z"
    mac: ENC[AES256_GCM,data:iwTsssV+w8eHkrNZ/EHAICz6IHfgMMuM+luHf6LOH2/QOml4CqukNn1TFXFzz1wMGNbmJ0JDt9yDPDmMgFILWhIKsLCzkMA6ATNexY69Me8tpcsoeV4/HHAcyWdfcFOr1/lK/5dwCqtnALxExh12HnR6/4rUDFo8xF1lglfZTN0=,iv:y0DCrjMSdnFfmunACWbvVmDXNM0VDBadHJmVPTCGj/0=,tag:oVBGiNVOrf5BrR02K7+8GA==,type:str]
    version: 3.13.3
