apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: route53-credentials
    namespace: cert-manager
stringData:
    access-key-id: ENC[AES256_GCM,data:qWcjOWcO2opV/BXFKQ9ouoxilpg=,iv:8NqUaCxlT2XshmyAAvFYxb2tefzVfz+lvM0o9xkOJuk=,tag:rZqX2AV5iseRijmqNdt2Tg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:C//FycgN0oQr2yA6qXci/HMMbFKzwN5ASiq8kIrkqofMWCYYVChIyw==,iv:dVmhECbPFjfpqnaEQm5iJr2egc9jw2LdjJrHXJZrKes=,tag:N3awV0fYOlaFv2HZqIUhFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYlRjNURvSnZJTk0xRkl6
            bEdscEV5cEE3aTVmNEJYSTRVUlJteW0rTVVvCnoreFVBYk9YcktWaWxqdVNxbXZJ
            NDhaZktFOWhWVXZEbEVSMi9nREtKVGsKLS0tIHN1NEN5V3hMMHNtVWtuWGVvSjM5
            UWRqMS94d0lzZ1pzUHkwY0FSVW9VeU0KzzfXimrw8Ko2JJZeGnvYMtIVW6mqgEbC
            n07ljhArnj7jA+stiheFfF3qFk6UxZuWKkKD9PvAzZCY3slyDblI9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:24:48Z"
    mac: ENC[AES256_GCM,data:Yv6zZr6MbX4ozMOu8fAjylx9SapNqIpSGX9WSN4W8TzHPGVa0zpTDOF6KIGtkXeVfFER2a1/2xyCnC5xkfhAI8IbYtnaWNEmBbEMv8Zk1xbaYqQqpFlbwwZX1f2GpZ96H3haiIDoK6neRHMu/4GU38NS950nbo6XuSxU6Kvv/aQ=,iv:/FBs8WqysMcsfjZI/HILU3Sw0Wh7OMUBYUpG3T0jHVo=,tag:9pRy7awxJNGaUf6JwKjHhQ==,type:str]
    version: 3.13.3
