apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: route53-credentials
    namespace: cert-manager
stringData:
    access-key-id: ENC[AES256_GCM,data:WJaBgYgVKruCzbAP0wqC470rpsE=,iv:XXg97re68qHyuaz8qvYDMh39CMq024p3oOtsuHWOmRY=,tag:l8all0+HCtiE3OEstJFPRg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:dEkB5gR128jnYm58lxi9UHP1oiAENalYQPr5GuzpOIs/oZ6/YGT2hQ==,iv:fqGnkNJIpj8jE5K0APVw+rkSnUbRBtJHuldjTMu1kzM=,tag:iF03uxNboChDQLKAOqIv/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbTVuYTJReDBSM0MxSkg2
            YlM3WnFwYW9Ya1lCUGVyV2IrSnpVUVYxdzNrCkpxYmxVSHdCQU1OQkJPa3dmUk5T
            b1kwdUtpWVBCcVdWYTJoRlg0aDBqZVEKLS0tIGlwK0kvZVVDZm5aM29pRUZEaHFN
            aUQ5ZDQ1dGNHSSs1dDdwRWtWRm1DYlEKIXjFziVzy+HYom2Ml0bFMSVbw+Bqshud
            XuNYYNMlGMfieTa3sdLxMhgRp6MJoFCOZMFJ9Rlv21cGAxP9iikU5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:14:50Z"
    mac: ENC[AES256_GCM,data:i2r6y1jqNyoLv4aZxmb6pqdVdKkDE+0qwi4qDQOsCO0doaVmpM4dzHS9cEWw+9D0rv/BZ9JaYFWuq9A9RIKTLRz/0HLnbMZWP/o2ZP3/6KW50R0yL+7h2Lg6pKRhbHLnFD0ZHkXQnzF828a/6J0TPqr+7slqc38jRpcbX+z4zBc=,iv:k+p3Zc9UW7SBxw1fl7xPqxOxjYe+aPI/HLWx1P4tpU4=,tag:95/4XOoDMjxH6qTArqci2g==,type:str]
    version: 3.13.3
