apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - smoke-test.sops.yaml
  - route53-credentials.sops.yaml
  - authentik-config.sops.yaml
  - grafana-admin.sops.yaml
