apiVersion: v1
kind: Secret
metadata:
    name: sops-smoke-test
    namespace: argocd
type: Opaque
stringData:
    test: ENC[AES256_GCM,data:AZcUo4bIMCzlSqdrxNBZvNYRNU2z,iv:Qb0u/ks4GksGK0rbrZdXV+F267tyVUM/wLymVqK3u6o=,tag:QuEsyKekz5N2tBhjiV2+pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUm9KSXFoamtkV2tzdjBG
            MWx2VStsWW5yRGFZVjlWV1lpSm9TUFJSZVFnCk5BUEtXOU03QlNraC9aQmhJMjVr
            Wkd6aDE4VGpJMFloZVVxczFJOTR4ejQKLS0tIFlSWmMweVJjSXN6R3lkY3pHVUhh
            MjF4SjZCalBweFlpeFNxUllrS1d1SEkKGopK3UCDh0YWHn3UGP8IFkLtFtsNSlS6
            rdMsXxkPA5k6qWXsceFzKuH3NNYJgjsGG1UzQYFS/BLpiHyvlej19A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:41:55Z"
    mac: ENC[AES256_GCM,data:n7IRH2Kg0dJ1eP4LjyBjNNzV597Tjo0A4E32VgWG2uQrj0DlssfD3L2zLDt1mlo88AwOMesHBWCZUOV0/nU5qF//eQSPq778hoQFFLGlJ0B+CYdmzVydzxS3aXB/njt8WXCtv6y8nD+Tk0R4ZWHvdy9oApPUMGCw4wbD+u0CILM=,iv:x3oJwUcgyfPJSvqnyeaiyTaVT5rFKsGOvYfTn+c+y4w=,tag:d0bd006VAmKv9RSuPfN8UA==,type:str]
    version: 3.13.3
