apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ten-gig
  namespace: metallb-system
spec:
  addresses:
    - 192.168.3.240-192.168.3.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ten-gig
  namespace: metallb-system
spec:
  ipAddressPools:
    - ten-gig