apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nas-nfs
  volumeMode: Filesystem
