apiVersion: v1
kind: Secret
metadata:
    name: nas-nfs-local-config
    namespace: argocd
type: Opaque
stringData:
    server: ENC[AES256_GCM,data:grMUBmH1FsN188tYUw==,iv:DtUPAoZin1R5A/e8PevYwfNWjn+ZuZycyUikItJAzf0=,tag:BceJwKvBvZHEZk/+uZIEtg==,type:str]
    share: ENC[AES256_GCM,data:amsngZlQOTVwuaBTipZebahYhA==,iv:BdzsFrjWdTCoaKSBimBDDqpn3d0UTfHltuzNBwTXlww=,tag:nHN9eXZfB89zB7gxQUD+UA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUTFDSjJWQzZ3MUFZeFNH
            U0RPOC9yMFFoeVJnVEVSeGhEV092RjJHdVJNCjFVSHdoNGRtUHgyNmRwQ216NjRa
            VGwraWFZNkNPWlFqdEFtYlR5RUtlYjAKLS0tIElNTnlHMUlIa1cwNW1GRG5jUXV1
            eG5jdG51K0R5Q1pQai9xOFMyZEU1NncKMIkaUsjLiUPL5dtGsj9AhnXNmXHFmYc2
            uNjnhVbhKJ6dBaDv0Yx1ca142JBW4GN/dPbgv+W4wf1QdrZJKxdfVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rph9048ac53jhhqajcz78lyyqku6u95l0gu5thc70uma7n256avqpgnxcj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:57:04Z"
    mac: ENC[AES256_GCM,data:vABBYF3h4L5LcSQZWJhE47dqYzhVhRSkV7BfkCVpkD2d3iIj8hCfK8IX4YreETHGTaaSHukynjgSF9dlotMo55/S6tqH5vk/CEQUpicrEos39v62a7XKirZgYJaXN4DndVNWq/oZs/IUm8GIdTRDDD3D2VzCx+thvTlrww/ipGs=,iv:XxhYVimqZUCJ9TIyFHxzra2MJhKQytEsUYBco1ocIZE=,tag:5aMZqhqAmmjGIEXfHrqB0g==,type:str]
    version: 3.13.3
