apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: nas-nfs-local-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - local-config.sops.yaml
