apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/application.yaml
  - storage/nfs-csi/application.yaml
  - storage/nas-nfs/application.yaml
  - networking/metallb/application.yaml
  - networking/metallb/config-application.yaml
  - networking/envoy-gateway/application.yaml
  - networking/envoy-gateway/config-application.yaml
  - applications/whoami.yaml
  - cert-manager/application.yaml
  - cert-manager/config-application.yaml
  - secrets/application.yaml
  - monitoring/metrics-server/application.yaml
  - monitoring/kubelet-csr-approver/application.yaml
