apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/application.yaml
  - storage/nfs-csi/application.yaml
  - storage/nas-nfs/application.yaml
  - networking/metallb/application.yaml
  - networking/metallb/config-application.yaml