apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: tyler180@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - selector:
          dnsZones:
            - k8s.749rmw.com
        dns01:
          route53:
            region: us-west-2
            hostedZoneID: Z04272303NZ93YPTT8MBI
            accessKeyIDSecretRef:
              name: route53-credentials
              key: access-key-id
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
