apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-csr-approver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://postfinance.github.io/kubelet-csr-approver
    chart: kubelet-csr-approver
    targetRevision: "1.2.15"
    helm:
      releaseName: kubelet-csr-approver
      valuesObject:
        providerRegex: '^node-[0-9]+$'
        providerIpPrefixes:
          - 192.0.2.0/24
        bypassDnsResolution: true
        skipDenyStep: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
