apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.3.128
  share: /volume2/kubernetes
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
